// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH5jBiUpiUKFMz_kEi_mlD_G6eh9kDe-s',
    appId: '1:645971394679:web:ca7c361468dec9d322c672',
    messagingSenderId: '645971394679',
    projectId: 'flutter-testing-67395',
    authDomain: 'flutter-testing-67395.firebaseapp.com',
    storageBucket: 'flutter-testing-67395.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabojjI1DOhA3vB8xipRcUlMWwi6nLcCs',
    appId: '1:645971394679:android:e61a37fca29e3d2f22c672',
    messagingSenderId: '645971394679',
    projectId: 'flutter-testing-67395',
    storageBucket: 'flutter-testing-67395.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpQmB2fgrIbFjjVcJSyiQ3Bf7hcJ3XHg',
    appId: '1:645971394679:ios:227b8ecb68c5134022c672',
    messagingSenderId: '645971394679',
    projectId: 'flutter-testing-67395',
    storageBucket: 'flutter-testing-67395.appspot.com',
    iosBundleId: 'com.example.flutterTesting',
  );
}
